language: node_js
sudo: false
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
before_script:
#  - npm install -g gulp
#  - npm install -g istanbul
script: npm run test-cov 
# Run test script, depending on istanbul install
#  - "test -n $(npm -ps ls istanbul) || npm test"
#  - "test -z $(npm -ps ls istanbul) || npm run-script test-travis"

after_script:
  - "npm install coveralls && nyc report --reporter=text-lcov | coveralls"