import BitMatrix from './BitMatrix';
import AnyMatrix from './AnyMatrix';
import AnyMatrixUseObject from './AnyMatrixUseObject';
declare const Int8Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Uint8Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Uint8ClampedMatrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Int16Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Uint16Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Int32Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Uint32Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Float32Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
declare const Float64Matrix: {
    new (width: number, height: number, defaultValue?: number): {
        _data: any;
        _dataInit(): void;
        clone(): any;
        getPrototypeData(): any[];
        fill(value: any): void;
        fillRow(row: number, value: any): void;
        fillColumn(column: number, v: any): void;
        get(x: number, y: number): any;
        set(x: number, y: number, v: any): void;
        getRow(row: number): any[];
        setRow(row: number, value: any[]): void;
        getColumn(column: number): any[];
        setColumn(column: number, value: any[]): void;
        cellForEach(fn: (arg0: any, arg1: number, arg2: number) => void): void;
        readonly width: number;
        readonly height: number;
        readonly total: number;
        Validator_row(row: any): void;
        Validator_column(column: any): void;
        Validator_xy(x: any, y: any): void;
        showView(): string;
        output(): string;
    };
    className: string;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, matrixLike: import("./Matrix").default.MatrixLike, callback?: (v: any, x: any, y: any) => any, thisArg?: any): T;
    from<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, arrayLike: any[], width?: number): T;
    input<T extends import("./Matrix").default>(this: new (a: any, b: any, c?: any) => T, base64: string): T;
    output(matrix: import("./Matrix").default): string;
};
export default BitMatrix;
export { AnyMatrix, AnyMatrixUseObject, BitMatrix, Int8Matrix, Uint8Matrix, Uint8ClampedMatrix, Int16Matrix, Uint16Matrix, Int32Matrix, Uint32Matrix, Float32Matrix, Float64Matrix, Uint8Matrix as ByteMatrix, };
